//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnBryce
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarType()
        {
            this.CarFleets = new HashSet<CarFleet>();
        }
    
        public int CarTypeID { get; set; }
        public int CarModelID { get; set; }
        public int Year { get; set; }
        public int GearTypeID { get; set; }
        public decimal DailyCost { get; set; }
        public decimal DailyLateCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarFleet> CarFleets { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual GearType GearType { get; set; }
    }
}
